# 03 SciML Intro

In [1]:
using Pkg
Pkg.activate("../") #activate the packes in the .toml files!

  Activating project at `c:\Users\olivi\Documents\SciMLBook`

Experiment: solving differntial equations with neural networks. Also look at physics-constrained neural networks.

## Getting started with ML using Flux

In [2]:
using Flux

## What is a Neural Network

NN(x)=W3σ2(W2σ1(W1x+b1)+b2)+b3
Example for R10 to R5

In [4]:
W = [randn(32,10),randn(32,32),randn(5,32)]
b = [zeros(32),zeros(32),zeros(5)]


3-element Vector{Vector{Float64}}:
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0]

In [6]:
simpleNN(x) = W[3]*tanh.(W[2]*tanh.(W[1]*x + b[1])+b[2])+b[3]
simpleNN(rand(10))

5-element Vector{Float64}:
 -2.004917870508095
 -2.611374672901566
 -2.429038844678645
 -8.084016728665889
  6.917759494018085

tanh used as activation layer!

### Defining Neural Networks with Flux.jl
Flux = on top of language-wide automatic differentiation!! -> Differentiable programming paradigm
https://fluxml.ai/


In [7]:
using Flux
NN2 = Chain(Dense(10 => 32, tanh),
            Dense(32 => 32, tanh),
            Dense(32 => 5))

Chain(
  Dense(10 => 32, tanh),                # 352 parameters
  Dense(32 => 32, tanh),                # 1_056 parameters
  Dense(32 => 5),                       # 165 parameters
)                   # Total: 6 arrays, 1_573 parameters, 6.520 KiB.

In [8]:
NN2(rand(10))

5-element Vector{Float64}:
  0.2262699139392644
 -0.9100160449399555
  0.1656047880802981
 -0.4958770996141305
  0.09852526830601774

Any anonymous function can be used as activation function!

In [9]:
NN3 = Chain(Dense(10 => 32,x->x^2),
            Dense(32 => 32,x->max(0,x)),
            Dense(32 => 5))
NN3(rand(10))

5-element Vector{Float64}:
  0.22135590836578306
  0.09583890629781955
 -0.6848427144030843
 -0.16245093028381108
 -0.03197636765839136

`x->max(0,x)` = RELU. Disadvantage = discontinuous! so maybe not the best for sciml...